document.addEventListener('DOMContentLoaded',()=>{
 const root=document.documentElement,body=document.body,toggle=document.querySelector('[data-lang-toggle]'),nav=document.querySelector('.main-nav'),menu=document.querySelector('.menu-toggle');
 const setLanguage=lang=>{const ar=lang==='ar';root.lang=lang;root.dir=ar?'rtl':'ltr';body.classList.toggle('arabic',ar);document.querySelectorAll('[data-en][data-ar]').forEach(el=>el.innerHTML=el.dataset[lang]);toggle.textContent=ar?'EN':'عربي';toggle.setAttribute('aria-label',ar?'Switch to English':'التبديل إلى العربية');localStorage.setItem('lexonz-language',lang);window.ScrollTrigger?.refresh()};
 const setMenu=open=>{nav.classList.toggle('open',open);menu.classList.toggle('active',open);body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Close menu':'Open menu')};
 toggle.addEventListener('click',()=>setLanguage(root.lang==='ar'?'en':'ar'));menu.addEventListener('click',()=>setMenu(!nav.classList.contains('open')));nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));setLanguage(localStorage.getItem('lexonz-language')||'en');
 document.addEventListener('keydown',event=>{if(event.key==='Escape')setMenu(false)});
 let lenis;
 if(window.Lenis){lenis=new Lenis({duration:1.2,smoothWheel:true});lenis.on('scroll',window.ScrollTrigger?.update);window.gsap?.ticker.add(t=>lenis.raf(t*1000));window.gsap?.ticker.lagSmoothing(0)}
 document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',event=>{
  const target=document.querySelector(link.getAttribute('href'));
  if(!target)return;
  event.preventDefault();
  setMenu(false);
  if(lenis)lenis.scrollTo(target,{duration:1.45,easing:t=>Math.min(1,1.001-Math.pow(2,-10*t)),lock:true});
  else target.scrollIntoView({behavior:'smooth',block:'start'});
  history.replaceState(null,'',link.getAttribute('href'));
 }));
 if(!window.gsap)return;gsap.registerPlugin(ScrollTrigger);const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 gsap.timeline({onComplete:()=>document.querySelector('.loader')?.remove()}).to('.loader span',{width:190,duration:.65,ease:'power2.inOut'}).to('.loader img,.loader small',{opacity:0,y:-10,duration:.3}).to('.loader',{yPercent:-100,duration:.8,ease:'power4.inOut'}).from('.hero-reveal',{y:45,opacity:0,duration:.8,stagger:.12,ease:'power3.out'},'-=.25');
 if(reduce)return;
 gsap.to('.hero-media',{yPercent:13,scale:1.12,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:true}});
 gsap.to('.speed-lines',{xPercent:12,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:true}});
 if(innerWidth>800){gsap.to('.manifesto-track',{x:()=>-(document.querySelector('.manifesto-track').scrollWidth-innerWidth),ease:'none',scrollTrigger:{trigger:'.manifesto',start:'top top',end:'bottom bottom',scrub:1,pin:'.manifesto-track',invalidateOnRefresh:true}})}else{const mobilePanels=gsap.utils.toArray('.manifesto-panel').filter(panel=>getComputedStyle(panel).display!=='none');mobilePanels.forEach(panel=>ScrollTrigger.create({trigger:panel,start:'top 55%',end:'bottom 45%',toggleClass:{targets:panel,className:'is-current'}}));mobilePanels.slice(1).forEach(panel=>gsap.from(panel,{yPercent:10,borderRadius:'22px 22px 0 0',ease:'none',scrollTrigger:{trigger:panel,start:'top bottom',end:'top top',scrub:.65}}));gsap.timeline({scrollTrigger:{trigger:'.panel-intro',start:'top 72%',once:true}}).from('.panel-intro .micro',{x:-24,opacity:0,duration:.45}).from('.panel-intro h2',{y:45,opacity:0,duration:.7,ease:'power3.out'},'-=.18').from('.mobile-telemetry span',{y:15,opacity:0,stagger:.1,duration:.4},'-=.25').fromTo('.panel-intro .giant-index',{scale:.72,opacity:0},{scale:1,opacity:1,duration:1,ease:'power3.out'},'-=.65');gsap.to('.panel-intro .giant-index',{yPercent:-12,ease:'none',scrollTrigger:{trigger:'.panel-intro',start:'top bottom',end:'bottom top',scrub:.7}});gsap.utils.toArray('.panel-copy').filter(panel=>getComputedStyle(panel).display!=='none').forEach(panel=>gsap.from(panel.querySelectorAll('.mobile-manifesto-copy > *'),{y:40,opacity:0,stagger:.12,duration:.7,ease:'power3.out',scrollTrigger:{trigger:panel,start:'top 58%',once:true}}));gsap.fromTo('.panel-image img',{scale:1.2},{scale:1.08,duration:1.4,ease:'power3.out',scrollTrigger:{trigger:'.panel-image',start:'top 62%',once:true}})}
 gsap.utils.toArray('.stage').forEach((el,i)=>{gsap.from(el,{y:65,opacity:0,duration:.8,delay:i*.08,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 82%'}});gsap.from(el.querySelector('.stage-line i'),{xPercent:-500,duration:1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 78%'}})});
 gsap.from('.inside-head > *',{y:55,opacity:0,stagger:.12,duration:.9,ease:'power3.out',scrollTrigger:{trigger:'.inside-head',start:'top 78%'}});gsap.utils.toArray('.inside-shot').forEach((el,i)=>gsap.from(el,{y:70,opacity:0,duration:.8,delay:(i%3)*.08,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 88%'}}));
 gsap.to('.impact-media',{yPercent:15,ease:'none',scrollTrigger:{trigger:'.impact',start:'top bottom',end:'bottom top',scrub:true}});gsap.from('.impact-copy > *',{y:60,opacity:0,stagger:.12,duration:1,scrollTrigger:{trigger:'.impact-copy',start:'top 70%'}});gsap.to('.join-visual img',{yPercent:-12,ease:'none',scrollTrigger:{trigger:'.join',start:'top bottom',end:'bottom top',scrub:true}});gsap.from('.join-copy > *',{y:45,opacity:0,stagger:.1,duration:.8,scrollTrigger:{trigger:'.join-copy',start:'top 78%'}});
 const cursor=document.querySelector('.cursor');addEventListener('pointermove',e=>gsap.to(cursor,{x:e.clientX,y:e.clientY,duration:.18}));document.querySelectorAll('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>gsap.to(cursor,{scale:3,duration:.2}));el.addEventListener('mouseleave',()=>gsap.to(cursor,{scale:1,duration:.2}))});
});
