document.addEventListener('DOMContentLoaded',()=>{
 const body=document.body,root=document.documentElement,nav=document.querySelector('.main-nav'),menu=document.querySelector('.menu-toggle'),langToggle=document.querySelector('[data-lang-toggle]');
 const ar={
  "About": "من نحن",
  "Services": "خدماتنا",
  "The pathway": "المسار",
  "Inside Lexonz": "داخل ليكسونز",
  "LEXONZ / SERVICES": "ليكسونز / الخدمات",
  "ONE ECOSYSTEM.": "منظومة واحدة.",
  "LEXONZ / ON TRACK": "ليكسونز / على الحلبة",
  "SILVERSTONE · UK": "سيلفرستون · المملكة المتحدة",
  "FOCUS / 01": "تركيز / 01",
  "Scroll to explore": "مرّر للاستكشاف",
  "RIYADH · SAUDI ARABIA": "الرياض · المملكة العربية السعودية",
  "INVEST": "استثمار",
  "Investment & Partnerships": "الاستثمار والشراكات",
  "DEVELOP": "تطوير",
  "Talent & Performance": "المواهب والأداء",
  "MANAGE": "إدارة",
  "BUILD": "بناء",
  "Brands, Commercial & Digital": "العلامات التجارية والتطوير التجاري والرقمي",
  "CREATE": "إبداع",
  "Media, IP & Experiences": "الإعلام والملكية الفكرية والتجارب",
  "01 / INVEST": "01 / استثمار",
  "Motorsport Investment & Partnerships": "الاستثمار والشراكات في رياضة المحركات",
  "FOR INVESTORS": "للمستثمرين",
  "TEAMS": "الفرق",
  "RIGHTS HOLDERS": "أصحاب الحقوق",
  "OUR ROLE": "دورنا",
  "Explore 10 capabilities": "مجالات العمل · 10",
  "Driver Investment": "الاستثمار في السائقين",
  "Team Investment": "الاستثمار في الفرق",
  "Equity Partnerships": "الشراكات في ملكية الشركات",
  "Team Acquisitions": "الاستحواذ على الفرق",
  "Strategic Partnerships": "الشراكات الاستراتيجية",
  "Motorsport Ventures": "مشاريع رياضة المحركات",
  "International Motorsport Opportunities": "فرص رياضة المحركات الدولية",
  "Technical Partnerships": "الشراكات الفنية",
  "Commercial Partnerships": "الشراكات التجارية",
  "Supporting International Teams Entering Saudi Arabia": "دعم الفرق الدولية للعمل في السعودية",
  "CAPITAL / MOMENTUM": "رأس المال / الزخم",
  "02 / DEVELOP": "02 / تطوير",
  "Talent Development & Performance": "تطوير المواهب والأداء",
  "FOR DRIVERS": "للسائقين",
  "ENGINEERS": "المهندسون",
  "ACADEMIES": "الأكاديميات",
  "Explore 22 capabilities": "مجالات العمل · 22",
  "Driver Scouting": "اكتشاف السائقين",
  "Talent Identification": "تحديد المواهب الواعدة",
  "Driver Assessment": "تقييم السائقين",
  "Performance Support": "دعم الأداء",
  "Marketing and Commercial Talent Development": "تطوير المواهب التسويقية والتجارية",
  "DRIVER / PERFORMANCE": "السائق / الأداء",
  "03 / MANAGE": "03 / إدارة",
  "Driver, Career & Team Management": "إدارة السائقين والمسيرة الرياضية والفرق",
  "TALENT": "المواهب",
  "Explore 15 capabilities": "مجالات العمل · 15",
  "Driver Management": "إدارة السائقين",
  "Career Management": "إدارة المسيرة الرياضية",
  "Long-Term Career Planning": "التخطيط طويل المدى للمسيرة الرياضية",
  "Driver Representation": "تمثيل السائقين",
  "Commercial Management": "الإدارة التجارية",
  "Contract and Opportunity Management": "إدارة العقود والفرص",
  "Team Management": "إدارة الفرق",
  "Operational Support": "الدعم التشغيلي",
  "Commercial Strategy": "الاستراتيجية التجارية",
  "Strategic Development": "التطوير الاستراتيجي",
  "International Team Partnerships": "شراكات الفرق الدولية",
  "Saudi Market Entry Support": "دعم دخول السوق السعودي",
  "ROUTE / DIRECTION": "المسار / الاتجاه",
  "04 / BUILD": "04 / بناء",
  "FOR BRANDS": "للعلامات التجارية",
  "SPONSORS": "الرعاة",
  "TECH PARTNERS": "الشركاء التقنيون",
  "Explore 26 capabilities": "مجالات العمل · 26",
  "Driver Brand Strategy": "استراتيجية العلامة الشخصية للسائق",
  "Personal Branding": "بناء العلامة الشخصية",
  "Brand Identity": "هوية العلامة التجارية",
  "Websites and Digital Presence": "المواقع والحضور الرقمي",
  "Content, PR and Media Strategy": "استراتيجية المحتوى والعلاقات العامة والإعلام",
  "Media Training": "التدريب الإعلامي",
  "Fan Engagement": "التواصل مع المشجعين",
  "Public Appearances": "الظهور العام",
  "Driver and Team Sponsorship": "رعاية السائقين والفرق",
  "Brand & Commercial Partnerships": "شراكات العلامات والشراكات التجارية",
  "Brand Activations": "تفعيل العلامات التجارية",
  "Content Partnerships": "شراكات المحتوى",
  "Sponsorship Management": "إدارة الرعاية",
  "Motorsport Digital Platforms": "منصات رياضة المحركات الرقمية",
  "Driver Databases & Profiles": "قواعد بيانات وملفات السائقين",
  "Talent Scouting Platforms": "منصات اكتشاف المواهب",
  "Performance Tracking": "تتبّع الأداء",
  "Team Management Systems": "أنظمة إدارة الفرق",
  "Motorsport Networking": "بناء العلاقات في رياضة المحركات",
  "Race Data Solutions": "حلول بيانات السباقات",
  "Digital Team Operations": "العمليات الرقمية للفرق",
  "B2B Motorsport Technology": "تقنيات رياضة المحركات للأعمال",
  "BRAND / PLATFORM": "العلامة / المنصة",
  "05 / CREATE": "05 / إبداع",
  "Media, Intellectual Property & Experiences": "الإعلام والملكية الفكرية والتجارب",
  "FOR AUDIENCES": "للجمهور",
  "BRANDS": "العلامات",
  "COMMUNITIES": "المجتمعات",
  "Explore 19 capabilities": "مجالات العمل · 19",
  "Before the Flag": "Before the Flag",
  "Documentary Series & Short Films": "سلاسل وثائقية وأفلام قصيرة",
  "Brand Films": "أفلام العلامات التجارية",
  "Driver Profiles": "ملفات تعريفية بالسائقين",
  "Behind-the-Scenes & Race-Weekend Content": "محتوى كواليس السباقات وفعالياتها",
  "Social-First & YouTube Content": "محتوى التواصل الاجتماعي ويوتيوب",
  "Photography & Interviews": "التصوير والمقابلات",
  "Motorsport Storytelling": "سرد قصص رياضة المحركات",
  "PR and Media Content": "محتوى العلاقات العامة والإعلام",
  "Corporate Events": "فعاليات الشركات",
  "Track Experiences & Test Days": "تجارب الحلبة وأيام الاختبار",
  "Karting Experiences": "تجارب الكارتنج",
  "Motorsport Conferences": "مؤتمرات رياضة المحركات",
  "Talent Showcases": "فعاليات إبراز المواهب",
  "Sponsor Experiences": "تجارب الرعاة",
  "STORY / EXPERIENCE": "القصة / التجربة",
  "Back to top": "العودة للأعلى",
  "Contact": "تواصل معنا",
  "Talk to our team": "تواصل مع فريقنا",
  "FIVE PILLARS.": "خمس ركائز.",
  "Investment, development, management, commercial strategy and media—five connected pillars supporting drivers, teams and partners through one motorsport company.": "الاستثمار والتطوير والإدارة والاستراتيجية التجارية والإعلام: خمس ركائز مترابطة تدعم السائقين والفرق والشركاء ضمن شركة واحدة لرياضة المحركات.",
  "Explore our services": "اكتشف خدماتنا",
  "THE LEXONZ APPROACH": "منهج ليكسونز",
  "Our five pillars work together, connecting preparation for competition with the investment, management and commercial support behind it.": "تتكامل ركائزنا الخمس لتربط الإعداد للمنافسة بما يدعمه من استثمار وإدارة وتطوير تجاري.",
  "Drivers & Teams": "السائقون والفرق",
  "We assess investment and partnership opportunities in drivers, teams and motorsport ventures, considering sporting objectives, commercial potential and long-term development.": "نقيّم فرص الاستثمار والشراكة في السائقين والفرق ومشاريع رياضة المحركات، وفق الأهداف الرياضية والإمكانات التجارية والتطوير طويل المدى.",
  "Connect investment decisions with sporting plans and commercial priorities.": "ربط القرارات الاستثمارية بالخطط الرياضية والأولويات التجارية.",
  "We develop drivers and motorsport professionals through assessment, technical preparation and performance support. Current driver activity centres on karting and Formula 4, with longer-term pathway planning towards Formula Regional, Formula 3 and Formula 2.": "نطوّر السائقين والمتخصصين في رياضة المحركات عبر التقييم والإعداد الفني ودعم الأداء. يتركز نشاط السائقين الحالي على الكارتنج وفورمولا 4، مع تخطيط طويل المدى للتدرّج نحو فورمولا ريجونال وفورمولا 3 وفورمولا 2.",
  "Match development to experience, performance and the requirements of the next category.": "مواءمة التطوير مع الخبرة والأداء ومتطلبات الفئة التالية.",
  "Single-Seater Driver Development": "تطوير سائقي السيارات أحادية المقعد",
  "Karting Driver Development": "تطوير سائقي الكارتنج",
  "Single-Seater Pathway Planning": "تخطيط مسارات السيارات أحادية المقعد",
  "GT, Endurance and Rally Pathway Planning": "تخطيط مسارات سباقات جي تي والتحمل والرالي",
  "Physical Conditioning": "الإعداد البدني",
  "Technical Skills Development": "تطوير المهارات الفنية",
  "Driver Career Planning": "تخطيط المسيرة الرياضية للسائق",
  "Motorsport Academy Programmes": "برامج أكاديميات رياضة المحركات",
  "Race Engineering Training": "تأهيل مهندسي السباقات",
  "Performance Engineering Training": "تأهيل مهندسي الأداء",
  "Data Engineering Training": "تأهيل مهندسي البيانات",
  "Mechanic and Technician Training": "تأهيل الميكانيكيين والفنيين",
  "Race Operations Training": "التدريب على عمليات السباقات",
  "Team Management Training": "التدريب على إدارة الفرق",
  "Sporting Staff Development": "تطوير الكوادر الرياضية",
  "Motorsport Media Training": "التدريب الإعلامي في رياضة المحركات",
  "International Development Opportunities": "فرص التطوير واكتساب الخبرة الدولية",
  "We support drivers and teams with career planning, representation, team selection and race operations. Sporting commitments, contracts and commercial activity are coordinated around clear objectives.": "ندعم السائقين والفرق بتخطيط المسيرة الرياضية والتمثيل واختيار الفرق وعمليات السباقات، وننسّق المشاركات والعقود والأنشطة التجارية وفق أهداف واضحة.",
  "Keep career decisions, team operations and commercial commitments aligned.": "تنسيق قرارات المسيرة الرياضية وعمليات الفرق والالتزامات التجارية.",
  "Driver Placement with Teams": "تنسيق انضمام السائقين إلى الفرق",
  "Driver–Team Matching": "مواءمة السائقين مع الفرق المناسبة",
  "Race Operations Support": "دعم عمليات السباقات",
  "We develop driver and team brands, sponsorship proposals and digital platforms. Each connects a clear identity with relevant audiences, defined partner rights and practical activation plans.": "نبني العلامات التجارية للسائقين والفرق، ونطوّر عروض الرعاية والمنصات الرقمية. ونربط الهوية بالجمهور المستهدف وحقوق الشركاء وخطط تفعيل الرعاية.",
  "Give partners a clear proposition, defined rights and a plan for delivery.": "تقديم عرض شراكة واضح وحقوق محددة وخطة تنفيذ.",
  "Sponsorship Strategy & Partner Acquisition": "استراتيجية الرعاية واستقطاب الشركاء",
  "Driver Endorsement Agreements": "اتفاقيات الترويج للعلامات التجارية عبر السائقين",
  "Social Media Management": "إدارة وسائل التواصل الاجتماعي",
  "Branded Merchandise Development": "تطوير المنتجات التي تحمل العلامة التجارية",
  "We turn real motorsport activity into original films, editorial content and event experiences. From the paddock to the circuit, we tell the stories of the people and preparation behind competition.": "نحوّل النشاط الفعلي في رياضة المحركات إلى أفلام أصلية ومحتوى تحريري وتجارب في الفعاليات. ومن منطقة الفرق إلى الحلبة، نروي قصص الأشخاص والاستعدادات وراء المنافسة.",
  "Build stories and experiences around the sport, with a clear purpose and audience.": "إنتاج قصص وتجارب تستند إلى الرياضة وتخاطب جمهوراً محدداً بهدف واضح.",
  "Original Motorsport IP Development": "تطوير ملكية فكرية أصلية في رياضة المحركات",
  "Motorsport Hospitality & Hosted Dinners": "ضيافة رياضة المحركات وحفلات العشاء",
  "Driver Appearances & Fan Meetings": "مشاركات السائقين ولقاءات الجمهور",
  "FIVE PILLARS. ONE CONNECTED APPROACH.": "خمس ركائز. نهج متكامل.",
  "PLAN YOUR": "خطّط",
  "NEXT STEP.": "لخطوتك التالية.",
  "Saudi ambition. Connected through motorsport.": "طموح سعودي تجمعه رياضة المحركات.",
  "BUILT FOR MOTORSPORT": "من أجل رياضة المحركات",
  "LEXONZ / 01": "ليكسونز / 01",
  "LEXONZ / 02": "ليكسونز / 02"
};
 const textNodes=[];const walker=document.createTreeWalker(body,NodeFilter.SHOW_TEXT);let textNode;while(textNode=walker.nextNode()){if(textNode.nodeValue.trim())textNodes.push({node:textNode,en:textNode.nodeValue.trim()})}
 const setLanguage=lang=>{const isArabic=lang==='ar';root.lang=lang;root.dir=isArabic?'rtl':'ltr';body.classList.toggle('arabic',isArabic);textNodes.forEach(({node,en})=>{const translated=isArabic&&ar[en]?ar[en]:en;node.nodeValue=node.nodeValue.replace(node.nodeValue.trim(),translated)});langToggle.textContent=isArabic?'EN':'عربي';langToggle.setAttribute('aria-label',isArabic?'Switch to English':'التبديل إلى العربية');
 document.title=lang==='ar'?"خدمات رياضة المحركات | ليكسونز":"Motorsport Services | LEXONZ";
 document.querySelector('meta[name="description"]').content=lang==='ar'?"اكتشف ركائز خدمات ليكسونز الخمس: الاستثمار في رياضة المحركات وتطوير المواهب والإدارة والاستراتيجية التجارية والإعلام.":"Explore LEXONZ’s five connected service pillars: motorsport investment, talent development, management, commercial strategy and media.";
 nav.setAttribute('aria-label',lang==='ar'?'التنقل الرئيسي':'Main navigation');
 document.querySelector('.brand').setAttribute('aria-label',lang==='ar'?'ليكسونز — الصفحة الرئيسية':'LEXONZ home');
 const menuOpen=menu.getAttribute('aria-expanded')==='true';
 menu.setAttribute('aria-label',lang==='ar'?(menuOpen?'إغلاق القائمة':'فتح القائمة'):(menuOpen?'Close menu':'Open menu'));
 localStorage.setItem('lexonz-language',lang);window.ScrollTrigger?.refresh()};
 const setMenu=open=>{nav.classList.toggle('open',open);menu.classList.toggle('active',open);body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',root.lang==='ar'?(open?'إغلاق القائمة':'فتح القائمة'):(open?'Close menu':'Open menu'))};
 menu.addEventListener('click',()=>setMenu(!nav.classList.contains('open')));document.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});
 langToggle.addEventListener('click',()=>setLanguage(root.lang==='ar'?'en':'ar'));setLanguage(localStorage.getItem('lexonz-language')||'en');
 let lenis;if(window.Lenis){lenis=new Lenis({duration:1.2,smoothWheel:true});lenis.on('scroll',window.ScrollTrigger?.update);window.gsap?.ticker.add(t=>lenis.raf(t*1000));window.gsap?.ticker.lagSmoothing(0)}
 document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',e=>{const target=document.querySelector(link.getAttribute('href'));if(!target)return;e.preventDefault();setMenu(false);lenis?lenis.scrollTo(target,{duration:1.35,offset:0}):target.scrollIntoView({behavior:'smooth'});history.replaceState(null,'',link.getAttribute('href'))}));
 const pillars=[...document.querySelectorAll('.pillar')],indexLinks=[...document.querySelectorAll('.index-links a')],progress=document.querySelector('.service-progress'),progressLabel=document.querySelector('.progress-label');
 const pillarObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;const index=pillars.indexOf(entry.target);indexLinks.forEach((link,i)=>link.classList.toggle('active',i===index));progressLabel.textContent=String(index+1).padStart(2,'0');progress?.style.setProperty('--progress',`${index*25}%`)})},{rootMargin:'-35% 0px -55%'});
 pillars.forEach(pillar=>pillarObserver.observe(pillar));
 const progressObserver=new IntersectionObserver(([entry])=>progress?.classList.toggle('visible',entry.isIntersecting),{threshold:.01});progressObserver.observe(document.querySelector('.pillars'));
 if(!window.gsap){document.querySelector('.loader')?.remove();return}gsap.registerPlugin(ScrollTrigger);const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 gsap.timeline({onComplete:()=>document.querySelector('.loader')?.remove()}).to('.loader span',{width:190,duration:.55,ease:'power2.inOut'}).to('.loader img,.loader small',{opacity:0,y:-8,duration:.25}).to('.loader',{yPercent:-100,duration:.7,ease:'power4.inOut'}).from('.service-reveal',{y:45,opacity:0,duration:.8,stagger:.12,ease:'power3.out'},'-=.2');
 if(!reduce){gsap.to('.services-grid',{yPercent:12,ease:'none',scrollTrigger:{trigger:'.services-hero',start:'top top',end:'bottom top',scrub:true}});gsap.to('.services-visual-main img',{yPercent:-8,scale:1.04,ease:'none',scrollTrigger:{trigger:'.services-hero',start:'top top',end:'bottom top',scrub:true}});gsap.from('.services-visual-detail',{x:70,opacity:0,duration:1,ease:'power3.out',delay:1.25});gsap.utils.toArray('.pillar').forEach(pillar=>gsap.from(pillar.querySelectorAll('.pillar-title > *, .pillar-content > *'),{y:45,opacity:0,stagger:.08,duration:.75,ease:'power3.out',scrollTrigger:{trigger:pillar,start:'top 72%'}}))}
 const cursor=document.querySelector('.cursor');addEventListener('pointermove',e=>gsap.to(cursor,{x:e.clientX,y:e.clientY,duration:.18}));document.querySelectorAll('a,button,summary').forEach(el=>{el.addEventListener('mouseenter',()=>gsap.to(cursor,{scale:3,duration:.2}));el.addEventListener('mouseleave',()=>gsap.to(cursor,{scale:1,duration:.2}))});
});
