document.addEventListener('DOMContentLoaded',()=>{
 const body=document.body,root=document.documentElement,nav=document.querySelector('.main-nav'),menu=document.querySelector('.menu-toggle'),langToggle=document.querySelector('[data-lang-toggle]');
 const ar={
  'ONE CONNECTED PATHWAY':'مسار واحد مترابط','About':'من نحن','Services':'خدماتنا','The pathway':'المسار','Inside Lexonz':'داخل ليكسونز','Join the grid':'انضم للمسار','Start a conversation':'ابدأ الحوار',
  'LEXONZ / SERVICES':'ليكسونز / الخدمات','FIVE DISCIPLINES.':'خمسة مجالات.','ONE ECOSYSTEM.':'منظومة واحدة.','LEXONZ connects the sporting and business sides of motorsport—bringing investment, talent development, management, commercial strategy and media into one coordinated system.':'تربط ليكسونز بين الجانبين الرياضي والتجاري لرياضة المحركات، وتجمع الاستثمار وتطوير المواهب والإدارة والاستراتيجية التجارية والإعلام ضمن منظومة متكاملة.','Explore our capabilities':'اكتشف قدراتنا','LEXONZ / ON TRACK':'ليكسونز / على الحلبة','SILVERSTONE · UK':'سيلفرستون · المملكة المتحدة','FOCUS / 01':'تركيز / 01','Scroll to explore':'مرّر للاستكشاف','RIYADH · SAUDI ARABIA':'الرياض · المملكة العربية السعودية',
  'THE LEXONZ SYSTEM':'منظومة ليكسونز','Five connected disciplines supporting drivers, teams, partners and motorsport ventures—from early development to competition and long-term value.':'خمسة مجالات مترابطة تدعم السائقين والفرق والشركاء ومشاريع رياضة المحركات، من التطوير المبكر إلى المنافسة والقيمة طويلة المدى.','INVEST':'استثمار','Investment & Partnerships':'الاستثمار والشراكات','DEVELOP':'تطوير','Talent & Performance':'المواهب والأداء','MANAGE':'إدارة','Drivers, Careers & Teams':'السائقون والمسيرات والفرق','BUILD':'بناء','Brands, Commercial & Digital':'العلامات والتجاري والرقمي','CREATE':'إبداع','Media, IP & Experiences':'الإعلام والملكية الفكرية والتجارب',
  '01 / INVEST':'01 / استثمار','Motorsport Investment & Partnerships':'الاستثمار والشراكات في رياضة المحركات','FOR INVESTORS':'للمستثمرين','TEAMS':'الفرق','RIGHTS HOLDERS':'أصحاب الحقوق','We assess selected opportunities around drivers, teams and motorsport ventures, looking for a clear sporting purpose, responsible structure and credible route to growth.':'نقيّم الفرص المختارة المرتبطة بالسائقين والفرق ومشاريع رياضة المحركات، بحثاً عن هدف رياضي واضح وهيكل مسؤول ومسار واقعي للنمو.','OUR ROLE':'دورنا','Bring sporting, commercial and market considerations into the same investment decision.':'نجمع الاعتبارات الرياضية والتجارية والسوقية ضمن قرار استثماري واحد.','Explore 10 capabilities':'اكتشف 10 قدرات','Driver Investment':'الاستثمار في السائقين','Team Investment':'الاستثمار في الفرق','Equity Partnerships':'شراكات الملكية','Team Acquisitions':'الاستحواذ على الفرق','Strategic Partnerships':'الشراكات الاستراتيجية','Motorsport Ventures':'مشاريع رياضة المحركات','International Motorsport Opportunities':'فرص رياضة المحركات الدولية','Technical Partnerships':'الشراكات التقنية','Commercial Partnerships':'الشراكات التجارية','Supporting International Teams Entering Saudi Arabia':'دعم الفرق الدولية لدخول السوق السعودي','CAPITAL / MOMENTUM':'رأس المال / الزخم',
  '02 / DEVELOP':'02 / تطوير','Talent Development & Performance':'تطوير المواهب والأداء','FOR DRIVERS':'للسائقين','ENGINEERS':'المهندسون','ACADEMIES':'الأكاديميات','We build structured development plans across motorsport. Our current work includes progression from karting into Formula 4 and toward Formula 3 and Formula 2, while the same disciplined approach applies to GT, endurance, rally and other categories.':'نبني خطط تطوير منظمة عبر رياضة المحركات. يشمل عملنا الحالي الانتقال من الكارتنج إلى فورمولا 4 ثم نحو فورمولا 3 وفورمولا 2، مع تطبيق المنهج المنظم نفسه على سباقات GT والتحمل والرالي وغيرها.','Turn ambition into a practical program shaped by the driver, the discipline and the demands of the next level.':'نحوّل الطموح إلى برنامج عملي تصوغه احتياجات السائق والفئة ومتطلبات المستوى التالي.','Explore 22 capabilities':'اكتشف 22 قدرة','Driver Scouting':'اكتشاف السائقين','Talent Identification':'تحديد المواهب','Driver Assessment':'تقييم السائقين','Formula Driver Development':'تطوير سائقي الفورمولا','Karting Development':'تطوير الكارتنج','F4, F3 and F2 Pathways':'مسارات فورمولا 4 و3 و2','GT, Endurance and Rally Pathways':'مسارات GT والتحمل والرالي','Technical Development':'التطوير التقني','Physical Development':'الإعداد البدني','Performance Support':'دعم الأداء','Career Pathway Planning':'تخطيط المسار المهني','Motorsport Academy Programs':'برامج أكاديميات رياضة المحركات','Race Engineering Development':'تطوير هندسة السباقات','Performance Engineering Development':'تطوير هندسة الأداء','Data Engineering Development':'تطوير هندسة البيانات','Mechanics and Technical Development':'تطوير الميكانيكيين والكفاءات التقنية','Motorsport Operations Development':'تطوير عمليات رياضة المحركات','Team Management Development':'تطوير إدارة الفرق','Sporting Personnel Development':'تطوير الكوادر الرياضية','Motorsport Media Development':'تطوير إعلام رياضة المحركات','Marketing and Commercial Talent Development':'تطوير المواهب التسويقية والتجارية','International Experience Pathways':'مسارات الخبرة الدولية','DRIVER / PERFORMANCE':'السائق / الأداء',
  '03 / MANAGE':'03 / إدارة','Driver, Career & Team Management':'إدارة السائقين والمسيرات والفرق','TALENT':'المواهب','We coordinate the sporting, operational and commercial decisions around a motorsport career, with each move assessed against the driver’s current level and long-term direction.':'ننسّق القرارات الرياضية والتشغيلية والتجارية المحيطة بمسيرة رياضة المحركات، ونقيّم كل خطوة وفق مستوى السائق الحالي واتجاهه طويل المدى.','Create continuity between development, team selection, contracts, competition and commercial commitments.':'نحقق الترابط بين التطوير واختيار الفريق والعقود والمنافسات والالتزامات التجارية.','Explore 15 capabilities':'اكتشف 15 قدرة','Driver Management':'إدارة السائقين','Career Management':'إدارة المسيرة','Long-Term Career Planning':'تخطيط المسيرة طويلة المدى','Driver Representation':'تمثيل السائقين','Team Placement':'اختيار الفريق المناسب','Team-Driver Matchmaking':'مواءمة الفرق والسائقين','Commercial Management':'الإدارة التجارية','Contract and Opportunity Management':'إدارة العقود والفرص','Team Management':'إدارة الفرق','Operational Support':'الدعم التشغيلي','Motorsport Operations Support':'دعم عمليات رياضة المحركات','Commercial Strategy':'الاستراتيجية التجارية','Strategic Development':'التطوير الاستراتيجي','International Team Partnerships':'شراكات الفرق الدولية','Saudi Market Entry Support':'دعم دخول السوق السعودي','ROUTE / DIRECTION':'المسار / الاتجاه',
  '04 / BUILD':'04 / بناء','FOR BRANDS':'للعلامات التجارية','SPONSORS':'الرعاة','TECH PARTNERS':'الشركاء التقنيون','We shape clear driver and team identities, sponsorship propositions and digital platforms that help partners understand the story, audience and potential value.':'نصوغ هويات واضحة للسائقين والفرق، وعروض رعاية ومنصات رقمية تساعد الشركاء على فهم القصة والجمهور والقيمة المحتملة.','Build the tools and commercial structure needed to present credible partnership opportunities.':'نبني الأدوات والهيكل التجاري اللازمين لتقديم فرص شراكة موثوقة.','Explore 26 capabilities':'اكتشف 26 قدرة','Driver Brand Strategy':'استراتيجية علامة السائق','Personal Branding':'العلامة الشخصية','Brand Identity':'هوية العلامة','Social Media':'وسائل التواصل الاجتماعي','Websites and Digital Presence':'المواقع والحضور الرقمي','Content, PR and Media Strategy':'استراتيجية المحتوى والعلاقات العامة والإعلام','Media Training':'التدريب الإعلامي','Fan Engagement':'تفاعل الجماهير','Public Appearances':'الظهور العام','Merchandise Development':'تطوير المنتجات','Sponsorship Strategy & Acquisition':'استراتيجية الرعاية واستقطابها','Driver and Team Sponsorship':'رعاية السائقين والفرق','Driver Endorsements':'تأييدات السائقين','Brand & Commercial Partnerships':'شراكات العلامات والشراكات التجارية','Brand Activations':'تفعيل العلامات التجارية','Content Partnerships':'شراكات المحتوى','Sponsorship Management':'إدارة الرعاية','Motorsport Digital Platforms':'منصات رياضة المحركات الرقمية','Driver Databases & Profiles':'قواعد بيانات وملفات السائقين','Talent Scouting Platforms':'منصات اكتشاف المواهب','Performance Tracking':'تتبّع الأداء','Team Management Systems':'أنظمة إدارة الفرق','Motorsport Networking':'شبكات التواصل في رياضة المحركات','Race Data Solutions':'حلول بيانات السباقات','Digital Team Operations':'العمليات الرقمية للفرق','B2B Motorsport Technology':'تقنيات رياضة المحركات للأعمال','BRAND / PLATFORM':'العلامة / المنصة',
  '05 / CREATE':'05 / إبداع','Media, Intellectual Property & Experiences':'الإعلام والملكية الفكرية والتجارب','FOR AUDIENCES':'للجمهور','BRANDS':'العلامات','COMMUNITIES':'المجتمعات','We document the work behind motorsport and develop stories, formats and experiences that give audiences meaningful access to drivers, teams and race weekends.':'نوثّق العمل خلف رياضة المحركات ونطوّر قصصاً وقوالب وتجارب تمنح الجمهور وصولاً ذا معنى إلى السائقين والفرق وعطلات السباق.','Translate real sporting activity into clear, engaging content and considered audience experiences.':'نحوّل النشاط الرياضي الحقيقي إلى محتوى واضح وجذاب وتجارب مدروسة للجمهور.','Explore 19 capabilities':'اكتشف 19 قدرة','Original Motorsport Intellectual Property':'ملكية فكرية أصلية لرياضة المحركات','Before the Flag':'قبل العلم','Documentary Series & Short Films':'سلاسل وثائقية وأفلام قصيرة','Brand Films':'أفلام العلامات التجارية','Driver Profiles':'ملفات السائقين','Behind-the-Scenes & Race-Weekend Content':'محتوى خلف الكواليس وعطلات السباق','Social-First & YouTube Content':'محتوى التواصل الاجتماعي ويوتيوب','Photography & Interviews':'التصوير والمقابلات','Motorsport Storytelling':'سرد قصص رياضة المحركات','PR and Media Content':'محتوى العلاقات العامة والإعلام','Corporate Events':'فعاليات الشركات','Motorsport Hospitality & Dinners':'ضيافة وعشاء رياضة المحركات','Track Experiences & Test Days':'تجارب الحلبة وأيام الاختبار','Karting Experiences':'تجارب الكارتنج','Driver Appearances & Meet and Greets':'ظهور السائقين ولقاءات الجمهور','Motorsport Conferences':'مؤتمرات رياضة المحركات','Talent Showcases':'عروض المواهب','Sponsor Experiences':'تجارب الرعاة','STORY / EXPERIENCE':'القصة / التجربة',
  'ONE MOTORSPORT ECOSYSTEM. FIVE CONNECTED DISCIPLINES.':'منظومة واحدة لرياضة المحركات. خمسة مجالات مترابطة.','BUILD THE':'ابنِ','NEXT STEP.':'الخطوة التالية.','Connecting Saudi talent and opportunity across motorsport.':'نربط المواهب والفرص السعودية عبر منظومة رياضة المحركات.','Back to top ↑':'العودة للأعلى ↑'
 };
 const textNodes=[];const walker=document.createTreeWalker(body,NodeFilter.SHOW_TEXT);let textNode;while(textNode=walker.nextNode()){if(textNode.nodeValue.trim())textNodes.push({node:textNode,en:textNode.nodeValue.trim()})}
 const setLanguage=lang=>{const isArabic=lang==='ar';root.lang=lang;root.dir=isArabic?'rtl':'ltr';body.classList.toggle('arabic',isArabic);textNodes.forEach(({node,en})=>{const translated=isArabic&&ar[en]?ar[en]:en;node.nodeValue=node.nodeValue.replace(node.nodeValue.trim(),translated)});langToggle.textContent=isArabic?'EN':'عربي';langToggle.setAttribute('aria-label',isArabic?'Switch to English':'التبديل إلى العربية');localStorage.setItem('lexonz-language',lang);window.ScrollTrigger?.refresh()};
 const setMenu=open=>{nav.classList.toggle('open',open);menu.classList.toggle('active',open);body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu')};
 menu.addEventListener('click',()=>setMenu(!nav.classList.contains('open')));document.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});
 langToggle.addEventListener('click',()=>setLanguage(root.lang==='ar'?'en':'ar'));setLanguage(localStorage.getItem('lexonz-language')||'en');
 let lenis;if(window.Lenis){lenis=new Lenis({duration:1.2,smoothWheel:true});lenis.on('scroll',window.ScrollTrigger?.update);window.gsap?.ticker.add(t=>lenis.raf(t*1000));window.gsap?.ticker.lagSmoothing(0)}
 document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',e=>{const target=document.querySelector(link.getAttribute('href'));if(!target)return;e.preventDefault();setMenu(false);lenis?lenis.scrollTo(target,{duration:1.35,offset:0}):target.scrollIntoView({behavior:'smooth'});history.replaceState(null,'',link.getAttribute('href'))}));
 const pillars=[...document.querySelectorAll('.pillar')],indexLinks=[...document.querySelectorAll('.index-links a')],progress=document.querySelector('.service-progress'),progressLabel=document.querySelector('.progress-label');
 const pillarObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;const index=pillars.indexOf(entry.target);indexLinks.forEach((link,i)=>link.classList.toggle('active',i===index));progressLabel.textContent=String(index+1).padStart(2,'0');progress?.style.setProperty('--progress',`${index*25}%`)})},{rootMargin:'-35% 0px -55%'});
 pillars.forEach(pillar=>pillarObserver.observe(pillar));
 const progressObserver=new IntersectionObserver(([entry])=>progress?.classList.toggle('visible',entry.isIntersecting),{threshold:.01});progressObserver.observe(document.querySelector('.pillars'));
 if(!window.gsap){document.querySelector('.loader')?.remove();return}gsap.registerPlugin(ScrollTrigger);const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 gsap.timeline({onComplete:()=>document.querySelector('.loader')?.remove()}).to('.loader span',{width:190,duration:.55,ease:'power2.inOut'}).to('.loader img,.loader small',{opacity:0,y:-8,duration:.25}).to('.loader',{yPercent:-100,duration:.7,ease:'power4.inOut'}).from('.service-reveal',{y:45,opacity:0,duration:.8,stagger:.12,ease:'power3.out'},'-=.2');
 if(!reduce){gsap.to('.services-grid',{yPercent:12,ease:'none',scrollTrigger:{trigger:'.services-hero',start:'top top',end:'bottom top',scrub:true}});gsap.to('.services-visual-main img',{yPercent:-8,scale:1.04,ease:'none',scrollTrigger:{trigger:'.services-hero',start:'top top',end:'bottom top',scrub:true}});gsap.from('.services-visual-detail',{x:70,opacity:0,duration:1,ease:'power3.out',delay:1.25});gsap.utils.toArray('.pillar').forEach(pillar=>gsap.from(pillar.querySelectorAll('.pillar-title > *, .pillar-content > *'),{y:45,opacity:0,stagger:.08,duration:.75,ease:'power3.out',scrollTrigger:{trigger:pillar,start:'top 72%'}}))}
 const cursor=document.querySelector('.cursor');addEventListener('pointermove',e=>gsap.to(cursor,{x:e.clientX,y:e.clientY,duration:.18}));document.querySelectorAll('a,button,summary').forEach(el=>{el.addEventListener('mouseenter',()=>gsap.to(cursor,{scale:3,duration:.2}));el.addEventListener('mouseleave',()=>gsap.to(cursor,{scale:1,duration:.2}))});
});
