document.addEventListener('DOMContentLoaded',()=>{
 const body=document.body,nav=document.querySelector('.main-nav'),menu=document.querySelector('.menu-toggle');
 const setMenu=open=>{nav.classList.toggle('open',open);menu.classList.toggle('active',open);body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu')};
 menu.addEventListener('click',()=>setMenu(!nav.classList.contains('open')));document.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});
 let lenis;if(window.Lenis){lenis=new Lenis({duration:1.2,smoothWheel:true});lenis.on('scroll',window.ScrollTrigger?.update);window.gsap?.ticker.add(t=>lenis.raf(t*1000));window.gsap?.ticker.lagSmoothing(0)}
 document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',e=>{const target=document.querySelector(link.getAttribute('href'));if(!target)return;e.preventDefault();setMenu(false);lenis?lenis.scrollTo(target,{duration:1.35,offset:0}):target.scrollIntoView({behavior:'smooth'});history.replaceState(null,'',link.getAttribute('href'))}));
 const pillars=[...document.querySelectorAll('.pillar')],indexLinks=[...document.querySelectorAll('.index-links a')],progress=document.querySelector('.service-progress'),progressLabel=document.querySelector('.progress-label');
 const pillarObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;const index=pillars.indexOf(entry.target);indexLinks.forEach((link,i)=>link.classList.toggle('active',i===index));progressLabel.textContent=String(index+1).padStart(2,'0');progress?.style.setProperty('--progress',`${index*25}%`)})},{rootMargin:'-35% 0px -55%'});
 pillars.forEach(pillar=>pillarObserver.observe(pillar));
 const progressObserver=new IntersectionObserver(([entry])=>progress?.classList.toggle('visible',entry.isIntersecting),{threshold:.01});progressObserver.observe(document.querySelector('.pillars'));
 if(!window.gsap){document.querySelector('.loader')?.remove();return}gsap.registerPlugin(ScrollTrigger);const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 gsap.timeline({onComplete:()=>document.querySelector('.loader')?.remove()}).to('.loader span',{width:190,duration:.55,ease:'power2.inOut'}).to('.loader img,.loader small',{opacity:0,y:-8,duration:.25}).to('.loader',{yPercent:-100,duration:.7,ease:'power4.inOut'}).from('.service-reveal',{y:45,opacity:0,duration:.8,stagger:.12,ease:'power3.out'},'-=.2');
 if(!reduce){gsap.to('.services-grid',{yPercent:12,ease:'none',scrollTrigger:{trigger:'.services-hero',start:'top top',end:'bottom top',scrub:true}});gsap.to('.services-visual-main img',{yPercent:-8,scale:1.04,ease:'none',scrollTrigger:{trigger:'.services-hero',start:'top top',end:'bottom top',scrub:true}});gsap.from('.services-visual-detail',{x:70,opacity:0,duration:1,ease:'power3.out',delay:1.25});gsap.utils.toArray('.pillar').forEach(pillar=>gsap.from(pillar.querySelectorAll('.pillar-title > *, .pillar-content > *'),{y:45,opacity:0,stagger:.08,duration:.75,ease:'power3.out',scrollTrigger:{trigger:pillar,start:'top 72%'}}))}
 const cursor=document.querySelector('.cursor');addEventListener('pointermove',e=>gsap.to(cursor,{x:e.clientX,y:e.clientY,duration:.18}));document.querySelectorAll('a,button,summary').forEach(el=>{el.addEventListener('mouseenter',()=>gsap.to(cursor,{scale:3,duration:.2}));el.addEventListener('mouseleave',()=>gsap.to(cursor,{scale:1,duration:.2}))});
});
